### ISSUE TITLE
train_ddpg_gym.py doesn't work

### ISSUE THREAD

**Issue by Kenichiro-Yoshimi** [pfnet/chainerrl#76]
Got this error while trying to run train_ddpg_gym.py: 
__init__() got an unexpected keyword argument 'update_interval'

**Comment by muupan** [comment]
Oops, that's because on the master branch the argument name has been updated while on the pypi version it has not yet.

Until the pypi version is updated, there are two options:
- install chainerrl from the master branch and use examples in the master branch
- install chainerrl via pip and use examples in https://github.com/pfnet/chainerrl/tree/v0.1.0.

**Comment by Kenichiro-Yoshimi** [comment]
I am trying the latest version from the master head in git, and this is working. Thank you for your help.
